/**
 * Certificate configuration - Single source of truth
 *
 * All certificate-related constants are defined here.
 * Import this file wherever certificate paths are needed.
 */

import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

// Project root is 2 levels up from lib/config/
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
export const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

// Certificate filenames (generated by mkcert)
// The "+N" suffix indicates number of additional SANs beyond localhost
export const CERT_FILENAME = "localhost+4.pem";
export const KEY_FILENAME = "localhost+4-key.pem";

// Full paths
export const CERT_PATH = path.join(PROJECT_ROOT, CERT_FILENAME);
export const KEY_PATH = path.join(PROJECT_ROOT, KEY_FILENAME);

// Hostnames included in the certificate (for reference)
export const CERT_HOSTNAMES = [
  "localhost",
  "edison",
  "192.168.1.10",
  "127.0.0.1",
  "::1",
];
