/**
 * Certificate configuration - Single source of truth
 *
 * All certificate-related constants are defined here.
 * Import this file wherever certificate paths are needed.
 */

import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

// Project root is 2 levels up from lib/config/
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
export const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

// Certificate filenames (generated by mkcert)
// The "+N" suffix indicates number of additional SANs beyond localhost
export const CERT_FILENAME = "localhost+4.pem";
export const KEY_FILENAME = "localhost+4-key.pem";

// Full paths
export const CERT_PATH = path.join(PROJECT_ROOT, CERT_FILENAME);
export const KEY_PATH = path.join(PROJECT_ROOT, KEY_FILENAME);

// Tailscale-issued (Let's Encrypt) certificate, produced by `tailscale cert`
// (scripts/setup-tailscale-cert.mjs). Served via SNI for *.ts.net names so
// remote tailnet devices get a trusted cert with NO custom CA installed.
// The actual TLS context selection lives in lib/config/tlsContext.mjs.
export const TAILSCALE_CERT_FILENAME = "tailscale.crt";
export const TAILSCALE_KEY_FILENAME = "tailscale.key";
export const TAILSCALE_CERT_PATH = path.join(PROJECT_ROOT, TAILSCALE_CERT_FILENAME);
export const TAILSCALE_KEY_PATH = path.join(PROJECT_ROOT, TAILSCALE_KEY_FILENAME);

// Hostnames included in the certificate (for reference)
export const CERT_HOSTNAMES = [
  "localhost",
  "edison",
  "192.168.1.10",
  "127.0.0.1",
  "::1",
];
