// lib/config/englishCommonWords.ts
//
// GENERATED — do not edit by hand. Regenerate with scripts/generate-common-words.mjs.
// Source: hermitdave/FrequencyWords (OpenSubtitles 2018) English 50k, top 9000 surface
// forms, normalized (lowercase + NFD accent-strip + apostrophe-fold) and split on
// non-alphanumerics, keeping sub-tokens >= 4 chars (same norm()/tokenizer as the
// LocalPosterMatcher). 8191 entries.
//
// Purpose: part of the "general word" gate for the local-poster fast-path. A spoken word
// that maps to a common English word cannot, on its own, fire a poster suggestion — it
// needs a show-domain keyword in context, or a 2nd corroborating token. Only a specific
// (non-general) token — a proper noun / made-up show name — fires alone. See commonWords.ts.

/** Common English words that must not single-handedly trigger a local-poster match. */
export const ENGLISH_COMMON_WORDS: ReadonlySet<string> = new Set([
  "aaah", "aaron", "abandon", "abandoned", "abby", "abducted", "abigail", "abilities",
  "ability", "able", "aboard", "abortion", "about", "above", "abraham", "abroad", "absence",
  "absent", "absolute", "absolutely", "absurd", "abuse", "abused", "academic", "academy",
  "accent", "accept", "acceptable", "accepted", "accepting", "access", "accident",
  "accidentally", "accidents", "accompany", "accomplice", "accomplish", "accomplished",
  "according", "account", "accountant", "accounting", "accounts", "accurate", "accusations",
  "accuse", "accused", "accusing", "achieve", "achieved", "achievement", "acid", "acknowledge",
  "acquaintance", "acquired", "acres", "across", "acted", "acting", "action", "actions",
  "activate", "activated", "active", "activities", "activity", "actor", "actors", "actress",
  "acts", "actual", "actually", "adam", "adams", "added", "addict", "addicted", "addiction",
  "adding", "addison", "addition", "additional", "address", "addressed", "addresses", "adjust",
  "administration", "admiral", "admire", "admired", "admission", "admit", "admitted", "adopt",
  "adopted", "adoption", "adorable", "adore", "adrian", "adult", "adults", "advance",
  "advanced", "advantage", "adventure", "adventures", "advertising", "advice", "advise",
  "advised", "advisor", "affair", "affairs", "affect", "affected", "affection", "affects",
  "afford", "afghanistan", "afraid", "africa", "african", "after", "afternoon", "afterwards",
  "again", "against", "aged", "agency", "agenda", "agent", "agents", "ages", "aggressive",
  "agnes", "agony", "agree", "agreed", "agreement", "agrees", "ahead", "ahem", "ahhh", "aids",
  "aircraft", "airplane", "airport", "aisle", "alan", "alarm", "alas", "alaska", "albert",
  "album", "alcohol", "alcoholic", "alec", "alert", "alex", "alexander", "alexis", "alfred",
  "alibi", "alice", "alicia", "alien", "aliens", "alike", "alison", "alive", "allah", "allen",
  "allergic", "alley", "alliance", "allies", "allison", "allow", "allowance", "allowed",
  "allowing", "allows", "ally", "almighty", "almost", "alone", "along", "alongside", "alpha",
  "already", "alright", "also", "altar", "alter", "altered", "alternative", "although",
  "altitude", "altogether", "always", "amanda", "amateur", "amazed", "amazing", "amazon",
  "ambassador", "amber", "ambition", "ambitious", "ambulance", "ambush", "amelia", "amen",
  "america", "american", "americans", "ammo", "ammunition", "among", "amongst", "amount",
  "amounts", "amsterdam", "amusing", "analysis", "ancestors", "anchor", "ancient", "anderson",
  "andre", "andrea", "andrew", "andrews", "andy", "angel", "angela", "angeles", "angelo",
  "angels", "anger", "angie", "angle", "angry", "animal", "animals", "anita", "ankle", "anna",
  "anne", "annie", "anniversary", "announce", "announced", "announcement", "announcer",
  "annoyed", "annoying", "annual", "anonymous", "another", "answer", "answered", "answering",
  "answers", "anthony", "antidote", "antique", "antoine", "anton", "antonio", "ants", "anxiety",
  "anxious", "anybody", "anyhow", "anymore", "anyone", "anything", "anytime", "anyway",
  "anyways", "anywhere", "apart", "apartment", "apartments", "apollo", "apologies", "apologise",
  "apologize", "apology", "apparent", "apparently", "appeal", "appear", "appearance",
  "appeared", "appears", "appetite", "applauding", "applause", "apple", "apples", "application",
  "applied", "apply", "appointed", "appointment", "appreciate", "appreciated", "appreciation",
  "approach", "approached", "approaches", "approaching", "appropriate", "approval", "approve",
  "approved", "approximately", "april", "arab", "arabic", "archer", "archie", "architect",
  "architecture", "arctic", "area", "areas", "aren", "arena", "argh", "argue", "argued",
  "arguing", "argument", "arguments", "arizona", "armed", "armies", "armor", "arms",
  "armstrong", "army", "arnold", "around", "arrange", "arranged", "arrangement", "arrangements",
  "arrest", "arrested", "arresting", "arrival", "arrive", "arrived", "arrives", "arriving",
  "arrogant", "arrow", "arrows", "arse", "artery", "arthur", "article", "articles", "artie",
  "artificial", "artillery", "artist", "artistic", "artists", "arts", "ashamed", "ashes",
  "ashley", "ashore", "asia", "asian", "aside", "asked", "asking", "asks", "asleep", "aspect",
  "aspirin", "assassin", "assassination", "assault", "assaulted", "assembly", "asses", "asset",
  "assets", "asshole", "assholes", "assigned", "assignment", "assist", "assistance",
  "assistant", "associate", "associated", "associates", "association", "assume", "assumed",
  "assuming", "assure", "assured", "asteroid", "astronaut", "asylum", "athlete", "atlanta",
  "atlantic", "atmosphere", "atomic", "attached", "attack", "attacked", "attacking", "attacks",
  "attempt", "attempted", "attempting", "attempts", "attend", "attended", "attending",
  "attention", "attic", "attitude", "attorney", "attract", "attracted", "attraction",
  "attractive", "auction", "audience", "audio", "audition", "audrey", "august", "aunt",
  "auntie", "aunty", "austin", "australia", "australian", "authentic", "author", "authorities",
  "authority", "authorized", "auto", "autograph", "automatic", "automatically", "autopsy",
  "autumn", "available", "avenge", "avenue", "average", "avery", "avoid", "avoided", "avoiding",
  "await", "awaiting", "awaits", "awake", "award", "awards", "aware", "away", "awesome",
  "awful", "awfully", "awhile", "awkward", "baba", "babe", "babies", "baby", "babysitter",
  "bachelor", "back", "backed", "background", "backing", "backpack", "backs", "backstage",
  "backup", "backwards", "backyard", "bacon", "bacteria", "badge", "badly", "baggage", "bags",
  "bail", "bailey", "bait", "bake", "baked", "baker", "bakery", "baking", "balance", "balcony",
  "bald", "ball", "ballet", "balloon", "balloons", "balls", "baltimore", "banana", "bananas",
  "band", "bandit", "bandits", "bands", "bang", "banging", "bangs", "bank", "banker",
  "bankrupt", "banks", "banned", "banner", "banquet", "barb", "barbara", "barbecue", "barber",
  "barbie", "bare", "barely", "bargain", "barge", "bark", "barking", "barks", "barn", "barnes",
  "barney", "baron", "barracks", "barrel", "barrier", "barry", "bars", "bart", "bartender",
  "base", "baseball", "based", "basement", "bash", "basic", "basically", "basis", "basket",
  "basketball", "bass", "bastard", "bastards", "batch", "bates", "bath", "bathing", "bathroom",
  "bathtub", "batman", "bats", "battalion", "batteries", "battery", "battle", "battlefield",
  "battles", "bauer", "baxter", "beach", "beacon", "beam", "bean", "beans", "bear", "beard",
  "bearing", "bears", "beast", "beasts", "beat", "beaten", "beating", "beatrice", "beats",
  "beautiful", "beautifully", "beauty", "became", "because", "becca", "beck", "beckett",
  "becky", "become", "becomes", "becoming", "bedroom", "beds", "bedtime", "beef", "been",
  "beep", "beeping", "beeps", "beer", "beers", "bees", "before", "began", "beggar", "begged",
  "begging", "begin", "beginning", "begins", "begun", "behalf", "behave", "behaved", "behaving",
  "behavior", "behaviour", "behind", "behold", "being", "beings", "belief", "beliefs",
  "believe", "believed", "believes", "believing", "bell", "bella", "belle", "bells", "belly",
  "belong", "belonged", "belongings", "belongs", "beloved", "below", "belt", "bench", "bend",
  "bender", "beneath", "benefit", "benefits", "benjamin", "bennett", "benny", "benson", "bent",
  "berlin", "bernard", "bernie", "bert", "beside", "besides", "best", "beth", "betray",
  "betrayal", "betrayed", "bets", "betsy", "better", "betting", "betty", "between", "beverly",
  "beware", "beyond", "bible", "bicycle", "bidding", "bigger", "biggest", "bike", "bikes",
  "bill", "billie", "billion", "billions", "bills", "billy", "bingo", "biological", "biology",
  "bird", "birds", "birth", "birthday", "biscuits", "bishop", "bitch", "bitches", "bite",
  "bites", "biting", "bits", "bitten", "bitter", "bizarre", "black", "blackmail", "blade",
  "blades", "blah", "blair", "blake", "blame", "blamed", "blaming", "blanche", "blank",
  "blanket", "blankets", "blaring", "blast", "bleed", "bleeding", "bleep", "blend", "bless",
  "blessed", "blessing", "blessings", "blew", "blind", "blink", "bliss", "block", "blocked",
  "blocking", "blocks", "blog", "bloke", "blond", "blonde", "blood", "bloody", "bloom",
  "blossom", "blow", "blowing", "blown", "blows", "blue", "blues", "bluff", "bluffing", "blunt",
  "board", "boarding", "boards", "boat", "boats", "bobby", "bodies", "body", "bodyguard",
  "boil", "boiling", "bold", "bollocks", "bolt", "bomb", "bombay", "bomber", "bombing", "bombs",
  "bond", "bonds", "bone", "bones", "bong", "bonnie", "bonus", "boobs", "book", "booked",
  "books", "boom", "boost", "boot", "booth", "boots", "booty", "booze", "border", "borders",
  "bore", "bored", "boring", "boris", "born", "borrow", "borrowed", "boss", "bosses", "boston",
  "both", "bother", "bothered", "bothering", "bothers", "bottle", "bottles", "bottom", "bought",
  "bounce", "bound", "boundaries", "bounty", "bourbon", "bout", "bowl", "bowling", "boxer",
  "boxes", "boxing", "boyd", "boyfriend", "boyfriends", "boys", "brace", "bracelet", "brad",
  "bradley", "brady", "brain", "brains", "brake", "brakes", "branch", "branches", "brand",
  "brandon", "brandy", "brass", "brat", "brave", "bravo", "brazil", "breach", "bread", "break",
  "breakdown", "breakfast", "breaking", "breaks", "breakthrough", "breast", "breasts", "breath",
  "breathe", "breathes", "breathing", "breed", "breeding", "breeze", "brenda", "brendan",
  "brennan", "brent", "brett", "brian", "bribe", "brick", "bricks", "bride", "bridge",
  "bridges", "bridget", "brief", "briefcase", "briefing", "briefly", "brien", "brigade",
  "briggs", "bright", "brilliant", "bring", "bringing", "brings", "britain", "british", "broad",
  "broadcast", "broadway", "brody", "broke", "broken", "brooke", "brooklyn", "brooks", "broom",
  "brothel", "brother", "brotherhood", "brothers", "brought", "brown", "bruce", "bruises",
  "bruno", "brush", "brutal", "bryan", "bryce", "bubble", "bubbles", "buck", "bucket", "bucks",
  "buddha", "buddies", "buddy", "budget", "buffalo", "buffy", "bugger", "bugs", "build",
  "building", "buildings", "built", "bull", "bullet", "bullets", "bullshit", "bully", "bump",
  "bumped", "bunch", "bunk", "bunker", "bunny", "burden", "bureau", "burger", "burgers",
  "burial", "buried", "burke", "burn", "burned", "burning", "burns", "burnt", "burst", "burt",
  "burton", "bury", "bush", "bushes", "business", "businesses", "businessman", "bust", "busted",
  "buster", "busting", "busy", "butch", "butcher", "butler", "butt", "butter", "butterflies",
  "butterfly", "button", "buttons", "butts", "buyer", "buying", "buys", "buzz", "buzzer",
  "buzzes", "buzzing", "cabbage", "cabin", "cabinet", "cable", "caesar", "cafe", "cafeteria",
  "cage", "caitlyn", "cake", "cakes", "caleb", "calendar", "calf", "california", "call",
  "called", "caller", "callie", "calling", "calls", "calm", "calvin", "came", "camel", "camera",
  "cameras", "cameron", "camille", "camp", "campaign", "campbell", "camping", "camps", "campus",
  "canada", "canadian", "canal", "cancel", "canceled", "cancelled", "cancer", "candidate",
  "candidates", "candle", "candles", "candy", "cane", "cannon", "cannot", "cans", "cant",
  "canvas", "canyon", "capable", "capacity", "cape", "capital", "captain", "capture",
  "captured", "carbon", "card", "cardinal", "cards", "care", "cared", "career", "careful",
  "carefully", "careless", "cares", "cargo", "caring", "carl", "carla", "carlo", "carlos",
  "carlton", "carmen", "carnival", "carol", "carolina", "caroline", "carpenter", "carpet",
  "carriage", "carrie", "carried", "carrier", "carries", "carrington", "carrot", "carrots",
  "carry", "carrying", "cars", "carson", "cart", "cartel", "carter", "cartoon", "carved",
  "case", "cases", "casey", "cash", "casino", "cassandra", "cassie", "cast", "casting",
  "castle", "casual", "casualties", "catch", "catches", "catching", "category", "cathedral",
  "catherine", "catholic", "cathy", "cats", "cattle", "caught", "cause", "caused", "causes",
  "causing", "caution", "cautious", "cavalry", "cave", "caves", "cease", "ceiling", "celebrate",
  "celebrated", "celebrating", "celebration", "celebrity", "cell", "cellar", "cellphone",
  "cells", "cement", "cemetery", "cent", "center", "central", "centre", "cents", "centuries",
  "century", "cereal", "ceremony", "certain", "certainly", "certificate", "chad", "chain",
  "chains", "chair", "chairman", "chairs", "challenge", "challenged", "challenges",
  "challenging", "chamber", "chambers", "champ", "champagne", "champion", "championship",
  "chan", "chance", "chancellor", "chances", "chandler", "chang", "change", "changed",
  "changes", "changing", "channel", "channels", "chanting", "chaos", "chap", "chapel",
  "chapter", "character", "characters", "charge", "charged", "charges", "charging", "charity",
  "charles", "charley", "charlie", "charlotte", "charm", "charming", "chart", "charts", "chase",
  "chased", "chasing", "chat", "chatter", "chattering", "chatting", "cheap", "cheaper", "cheat",
  "cheated", "cheating", "check", "checked", "checking", "checks", "cheek", "cheeks", "cheer",
  "cheerful", "cheering", "cheers", "cheese", "chef", "chelsea", "chemical", "chemicals",
  "chemistry", "chen", "cheque", "cherish", "cherry", "cheryl", "chess", "chest", "chester",
  "chew", "chewing", "chffffff", "chicago", "chick", "chicken", "chickens", "chicks", "chief",
  "child", "childhood", "childish", "children", "chili", "chill", "chilly", "chimes", "chin",
  "china", "chinese", "ching", "chip", "chips", "chirping", "chloe", "chocolate", "choi",
  "choice", "choices", "choir", "choke", "choking", "choose", "choosing", "chop", "chopped",
  "chopper", "chorus", "chose", "chosen", "chow", "chris", "christ", "christian", "christians",
  "christina", "christine", "christmas", "christopher", "chuck", "chuckle", "chuckles",
  "chuckling", "chun", "church", "churchill", "ciao", "cigar", "cigarette", "cigarettes",
  "cigars", "cindy", "cinema", "circle", "circles", "circuit", "circumstances", "circus",
  "cities", "citizen", "citizens", "city", "civil", "civilian", "civilians", "civilization",
  "civilized", "claim", "claimed", "claiming", "claims", "claire", "clamoring", "clan", "clap",
  "clapping", "clara", "clarence", "clark", "clarke", "class", "classes", "classic",
  "classical", "classified", "classroom", "classy", "clattering", "clatters", "claude",
  "claudia", "claus", "claw", "claws", "clay", "clayton", "clean", "cleaned", "cleaner",
  "cleaning", "clear", "clearance", "cleared", "clearing", "clearly", "clears", "clerk",
  "cleveland", "clever", "click", "clicking", "clicks", "client", "clients", "cliff", "climate",
  "climb", "climbed", "climbing", "clinic", "clinton", "clip", "clive", "clock", "close",
  "closed", "closely", "closer", "closes", "closest", "closet", "closing", "cloth", "clothes",
  "clothing", "cloud", "clouds", "clown", "clowns", "club", "clubs", "clue", "clues", "clumsy",
  "clyde", "coach", "coaches", "coal", "coast", "coat", "coats", "cocaine", "cock", "cocks",
  "cocktail", "coconut", "code", "codes", "cody", "coffee", "coffin", "coin", "coincidence",
  "coins", "coke", "colby", "cold", "cole", "colin", "collapse", "collapsed", "collar",
  "colleague", "colleagues", "collect", "collected", "collecting", "collection", "collective",
  "collector", "college", "collins", "colonel", "colony", "color", "colorado", "colored",
  "colors", "colour", "colours", "column", "coma", "comb", "combat", "combination", "combined",
  "come", "comedian", "comedy", "comes", "comet", "comfort", "comfortable", "comic", "comin",
  "coming", "command", "commander", "commanding", "commands", "comment", "comments",
  "commercial", "commission", "commissioner", "commit", "commitment", "committed", "committee",
  "committing", "common", "communicate", "communication", "communications", "communist",
  "communists", "community", "companies", "companion", "company", "compare", "compared",
  "comparison", "compartment", "compass", "compassion", "compensation", "compete", "competing",
  "competition", "competitive", "complain", "complained", "complaining", "complaint",
  "complaints", "complete", "completed", "completely", "complex", "complicated", "compliment",
  "compliments", "compound", "compromise", "compromised", "computer", "computers", "comrade",
  "comrades", "concentrate", "concentration", "concept", "concern", "concerned", "concerning",
  "concerns", "concert", "conclusion", "conclusions", "concrete", "condemned", "condition",
  "conditions", "condo", "condolences", "condom", "condoms", "conduct", "conducted",
  "conducting", "conference", "confess", "confessed", "confession", "confidence", "confident",
  "confidential", "confirm", "confirmation", "confirmed", "conflict", "confront", "confuse",
  "confused", "confusing", "confusion", "congrats", "congratulate", "congratulations",
  "congress", "congressman", "connect", "connected", "connecting", "connection", "connections",
  "connie", "connor", "conquer", "conrad", "conscience", "conscious", "consciousness",
  "consent", "consequences", "conservative", "consider", "considerable", "consideration",
  "considered", "considering", "consistent", "conspiracy", "constable", "constant",
  "constantly", "constitution", "construction", "consult", "consultant", "contact", "contacted",
  "contacts", "contain", "contained", "container", "contains", "contempt", "content",
  "contents", "contest", "context", "continent", "continue", "continued", "continues",
  "continuing", "contract", "contracts", "contrary", "contribution", "control", "controlled",
  "controlling", "controls", "convenience", "convenient", "convent", "convention",
  "conversation", "conversations", "convict", "convicted", "conviction", "convince",
  "convinced", "convincing", "cook", "cooked", "cookie", "cookies", "cooking", "cooks", "cool",
  "cooler", "coop", "cooper", "cooperate", "cooperation", "coordinates", "cope", "copies",
  "copper", "cops", "copy", "cord", "core", "corn", "corner", "corners", "coroner", "corporal",
  "corporate", "corporation", "corps", "corpse", "corpses", "correct", "corrected", "correctly",
  "corridor", "corrupt", "corruption", "cory", "cosmic", "cosmos", "cost", "costs", "costume",
  "costumes", "cottage", "cotton", "couch", "cough", "coughing", "coughs", "could", "couldn",
  "council", "counsel", "counselor", "count", "counted", "counter", "countess", "counting",
  "countless", "countries", "country", "countryside", "counts", "county", "coup", "couple",
  "couples", "courage", "courier", "course", "court", "courtesy", "courtney", "courtroom",
  "courts", "cousin", "cousins", "cover", "coverage", "covered", "covering", "covers", "coward",
  "cowards", "cowboy", "cows", "cozy", "crab", "crack", "cracked", "cracking", "crackling",
  "cracks", "craft", "craig", "crane", "crap", "crappy", "crash", "crashed", "crashes",
  "crashing", "crawford", "crawl", "crawling", "crazy", "creaking", "creaks", "cream", "create",
  "created", "creates", "creating", "creation", "creative", "creator", "creature", "creatures",
  "credit", "creek", "creep", "creeps", "creepy", "crew", "cricket", "cried", "cries", "crime",
  "crimes", "criminal", "criminals", "cripple", "crisis", "critical", "crook", "crooked",
  "crop", "cross", "crossed", "crosses", "crossing", "crow", "crowd", "crowded", "crowds",
  "crown", "crucial", "cruel", "cruise", "crush", "crushed", "cruz", "crying", "crystal",
  "cuba", "cuban", "cuff", "cuffs", "culprit", "cult", "cultural", "culture", "cunning", "cunt",
  "cupboard", "cups", "cure", "cured", "curfew", "curiosity", "curious", "curly", "currency",
  "current", "currently", "curry", "curse", "cursed", "curtain", "curtains", "curtis", "curve",
  "custody", "custom", "customer", "customers", "customs", "cute", "cuts", "cutting", "cycle",
  "cynthia", "cyrus", "daddy", "dagger", "daily", "daisy", "dale", "dallas", "dalton", "daly",
  "damage", "damaged", "dame", "damien", "dammit", "damn", "damned", "damon", "dana", "dance",
  "danced", "dancer", "dancers", "dances", "dancing", "dang", "danger", "dangerous", "dani",
  "daniel", "danielle", "danish", "danny", "dante", "daphne", "dare", "dared", "daring", "dark",
  "darkness", "darling", "darn", "darren", "darrin", "darryl", "darwin", "dash", "data",
  "database", "date", "dated", "dates", "dating", "daughter", "daughters", "dave", "david",
  "davis", "dawn", "dawson", "daylight", "days", "deacon", "dead", "deadline", "deadly", "deaf",
  "deal", "dealer", "dealers", "dealing", "deals", "dealt", "dean", "dear", "dearest", "dearly",
  "death", "deaths", "debate", "debbie", "debris", "debt", "debts", "decade", "decades",
  "deceased", "deceive", "deceived", "december", "decent", "decide", "decided", "decides",
  "decision", "decisions", "deck", "declare", "declared", "decline", "decorated", "dedicated",
  "deed", "deeds", "deep", "deeper", "deepest", "deeply", "deer", "defeat", "defeated",
  "defence", "defend", "defendant", "defending", "defense", "defensive", "define", "definite",
  "definitely", "definition", "degree", "degrees", "delay", "delayed", "delete", "delhi",
  "deliberately", "delicate", "delicious", "delight", "delighted", "delightful", "deliver",
  "delivered", "delivering", "delivery", "delta", "demand", "demanded", "demanding", "demands",
  "democracy", "democratic", "demon", "demons", "demonstrate", "demonstration", "denial",
  "denied", "denise", "dennis", "denny", "dental", "dentist", "denver", "deny", "denying",
  "department", "departure", "depend", "depending", "depends", "deposit", "depressed",
  "depressing", "depression", "depth", "depths", "deputy", "derek", "describe", "described",
  "description", "desert", "deserted", "deserve", "deserved", "deserves", "design", "designed",
  "designer", "designs", "desire", "desires", "desk", "despair", "desperate", "desperately",
  "despise", "despite", "dessert", "destination", "destined", "destiny", "destroy", "destroyed",
  "destroying", "destruction", "detail", "detailed", "details", "detect", "detected",
  "detective", "detectives", "detention", "determine", "determined", "detroit", "devastated",
  "develop", "developed", "developing", "development", "device", "devices", "devil", "devils",
  "devon", "devoted", "devotion", "dewey", "dexter", "diagnosis", "dial", "dialogue", "diamond",
  "diamonds", "diana", "diane", "diary", "dice", "dick", "dickhead", "didn", "died", "diego",
  "dies", "diet", "difference", "differences", "different", "differently", "difficult",
  "difficulties", "difficulty", "digging", "digital", "dignity", "dime", "dimension", "dine",
  "diner", "ding", "dings", "dining", "dinner", "dinosaur", "dinosaurs", "diplomatic", "direct",
  "directed", "direction", "directions", "directly", "director", "directors", "dirt", "dirty",
  "disabled", "disagree", "disappear", "disappearance", "disappeared", "disappearing",
  "disappears", "disappoint", "disappointed", "disappointing", "disappointment", "disaster",
  "discharge", "discharged", "discipline", "disco", "discount", "discover", "discovered",
  "discovery", "discreet", "discretion", "discuss", "discussed", "discussing", "discussion",
  "disease", "diseases", "disgrace", "disguise", "disgusting", "dish", "dishes", "dislike",
  "dismiss", "dismissed", "disorder", "dispatch", "display", "disposal", "disrespect",
  "distance", "distant", "distinguished", "distorted", "distract", "distracted", "distraction",
  "distress", "distribution", "district", "disturb", "disturbed", "disturbing", "ditch", "dive",
  "divide", "divided", "divine", "diving", "division", "divorce", "divorced", "dixon", "dizzy",
  "dock", "doctor", "doctors", "document", "documentary", "documents", "dodge", "does", "doesn",
  "dogs", "doin", "doing", "doll", "dollar", "dollars", "dolls", "dolly", "dome", "domestic",
  "dominic", "donald", "donate", "donation", "done", "dong", "donkey", "donna", "donnie",
  "donny", "donor", "donovan", "dont", "doom", "doomed", "door", "doorbell", "doors",
  "doorstep", "dope", "doris", "dorm", "dorothy", "dose", "double", "doubt", "doubts", "douche",
  "doug", "dough", "douglas", "dove", "down", "downstairs", "downtown", "doyle", "dozen",
  "dozens", "draft", "drag", "dragged", "dragging", "dragon", "dragons", "drain", "drake",
  "drama", "dramatic", "drank", "draw", "drawer", "drawing", "drawings", "drawn", "draws",
  "dreadful", "dream", "dreamed", "dreaming", "dreams", "dreamt", "dress", "dressed", "dresses",
  "dressing", "drew", "dried", "drift", "drill", "drink", "drinking", "drinks", "drive",
  "driven", "driver", "drivers", "drives", "driveway", "driving", "drone", "drop", "dropped",
  "dropping", "drops", "drove", "drown", "drowned", "drowning", "drug", "drugged", "drugs",
  "drum", "drums", "drunk", "drunken", "duchess", "duck", "ducks", "dude", "dudes", "duel",
  "duke", "dull", "dumb", "dummy", "dump", "dumped", "dumping", "duncan", "dunno", "during",
  "dust", "dusty", "dutch", "duties", "duty", "dwarf", "dwight", "dying", "dylan", "dynamic",
  "dynamite", "dynasty", "each", "eager", "eagle", "earl", "earlier", "early", "earn", "earned",
  "earrings", "ears", "earth", "earthquake", "ease", "easier", "easiest", "easily", "east",
  "easter", "eastern", "easy", "eaten", "eating", "eats", "echo", "echoing", "economic",
  "economy", "ecstasy", "eddie", "eden", "edgar", "edge", "edith", "edition", "editor",
  "educated", "education", "edward", "edwards", "eerie", "effect", "effective", "effects",
  "efficient", "effort", "efforts", "eggs", "egypt", "egyptian", "eight", "eighteen", "eighth",
  "einstein", "either", "elaborate", "elaine", "elbow", "elder", "elderly", "elderman",
  "elders", "eldest", "eleanor", "elected", "election", "elections", "electric", "electrical",
  "electricity", "electronic", "elegant", "element", "elementary", "elements", "elena",
  "elephant", "elephants", "elevator", "eleven", "eliminate", "eliminated", "elite",
  "elizabeth", "ella", "ellen", "ellie", "elliot", "ellis", "elsa", "else", "elsewhere",
  "elvis", "email", "embarrass", "embarrassed", "embarrassing", "embarrassment", "embassy",
  "embrace", "emergency", "emily", "emma", "emotion", "emotional", "emotionally", "emotions",
  "emperor", "empire", "employed", "employee", "employees", "employer", "employment", "empress",
  "empty", "encounter", "encourage", "encouraged", "ended", "ending", "endless", "ends",
  "endure", "enemies", "enemy", "energy", "enforcement", "engage", "engaged", "engagement",
  "engine", "engineer", "engineering", "engineers", "engines", "england", "english", "enjoy",
  "enjoyed", "enjoying", "enormous", "enough", "ensure", "enter", "entered", "entering",
  "enterprise", "enters", "entertain", "entertaining", "entertainment", "enthusiasm", "entire",
  "entirely", "entitled", "entrance", "entry", "envelope", "environment", "environmental",
  "envy", "epic", "episode", "equal", "equally", "equals", "equipment", "equipped",
  "equivalent", "erase", "erased", "eric", "erica", "erik", "erin", "ernest", "ernie", "errand",
  "error", "escape", "escaped", "escaping", "escort", "especially", "essay", "essence",
  "essential", "essentially", "establish", "established", "establishment", "estate", "esther",
  "estimate", "eternal", "eternity", "ethan", "ethel", "ethics", "eugene", "europe", "european",
  "euros", "evacuate", "evan", "evans", "evelyn", "even", "evening", "event", "events",
  "eventually", "ever", "every", "everybody", "everyday", "everyone", "everything",
  "everywhere", "evidence", "evil", "evolution", "evolved", "exact", "exactly", "exam",
  "examination", "examine", "examined", "example", "exams", "excellency", "excellent", "except",
  "exception", "exceptional", "exchange", "excited", "excitement", "exciting", "exclaiming",
  "exclaims", "exclusive", "excuse", "excuses", "execute", "executed", "execution", "executive",
  "exercise", "exhales", "exhausted", "exhibit", "exhibition", "exile", "exist", "existed",
  "existence", "exists", "exit", "exotic", "expand", "expect", "expectations", "expected",
  "expecting", "expects", "expedition", "expelled", "expense", "expenses", "expensive",
  "experience", "experienced", "experiences", "experiencing", "experiment", "experimental",
  "experiments", "expert", "expertise", "experts", "explain", "explained", "explaining",
  "explains", "explanation", "explode", "exploded", "explore", "explosion", "explosions",
  "explosive", "explosives", "expose", "exposed", "exposure", "express", "expressed",
  "expression", "exquisite", "extend", "extended", "extension", "extent", "extra", "extract",
  "extraordinary", "extreme", "extremely", "eyes", "fabric", "fabulous", "face", "facebook",
  "faced", "faces", "facial", "facilities", "facility", "facing", "fact", "factor", "factories",
  "factory", "facts", "fade", "faggot", "fail", "failed", "failing", "fails", "failure",
  "faint", "fainted", "fair", "fairly", "fairy", "faith", "faithful", "fake", "faking", "fall",
  "fallen", "falling", "falls", "false", "fame", "familiar", "families", "family", "famous",
  "fancy", "fang", "fanny", "fans", "fantasies", "fantastic", "fantasy", "fare", "farewell",
  "farm", "farmer", "farmers", "fart", "farther", "fascinated", "fascinating", "fashion",
  "fashioned", "fast", "faster", "fastest", "fatal", "fate", "father", "fathers", "fatty",
  "fault", "favor", "favorite", "favors", "favour", "favourite", "fear", "feared", "fearless",
  "fears", "feast", "feather", "feathers", "feature", "features", "february", "federal",
  "federation", "feds", "feed", "feedback", "feeding", "feeds", "feel", "feelin", "feeling",
  "feelings", "feels", "fees", "feet", "felicity", "felix", "fell", "fella", "fellas", "fellow",
  "fellows", "felony", "felt", "female", "females", "feminine", "fence", "fernando", "ferrari",
  "ferry", "festival", "fetch", "fever", "fewer", "fiance", "fiancee", "fiction", "field",
  "fields", "fierce", "fifteen", "fifth", "fifty", "fight", "fighter", "fighters", "fighting",
  "fights", "figure", "figured", "figures", "figuring", "file", "filed", "files", "filing",
  "fill", "filled", "filling", "film", "filmed", "filming", "films", "filth", "filthy", "final",
  "finale", "finally", "finals", "finance", "financial", "finch", "find", "finding", "finds",
  "fine", "finest", "finger", "fingerprints", "fingers", "finish", "finished", "finishing",
  "finn", "fiona", "fire", "fired", "fires", "fireworks", "firing", "firm", "first", "fish",
  "fisher", "fisherman", "fishing", "fist", "fits", "fitting", "fitz", "five", "fixed",
  "fixing", "flag", "flags", "flame", "flames", "flash", "flashlight", "flat", "flattered",
  "flavor", "fled", "flee", "fleet", "flesh", "fletcher", "flew", "flies", "flight", "flights",
  "flip", "flipped", "flirt", "flirting", "float", "floating", "flock", "flood", "flooded",
  "floor", "floors", "flora", "florence", "florida", "flour", "flow", "flower", "flowers",
  "flowing", "flown", "flows", "floyd", "fluid", "flush", "flute", "flying", "flynn", "foam",
  "focus", "focused", "fold", "folk", "folks", "follow", "followed", "followers", "following",
  "follows", "fond", "font", "food", "foods", "fool", "fooled", "fooling", "foolish", "fools",
  "foot", "footage", "football", "footprints", "footsteps", "forbid", "forbidden", "force",
  "forced", "forces", "forcing", "ford", "forehead", "foreign", "foreigner", "foreigners",
  "foreman", "forensic", "forensics", "forest", "forests", "forever", "forge", "forged",
  "forget", "forgetting", "forgive", "forgiven", "forgiveness", "forgot", "forgotten", "fork",
  "form", "formal", "formation", "formed", "former", "forms", "formula", "fort", "forth",
  "fortress", "fortunate", "fortunately", "fortune", "forty", "forward", "foster", "fought",
  "foul", "found", "foundation", "founded", "fountain", "four", "fourteen", "fourth",
  "fracture", "fragile", "frame", "framed", "fran", "france", "frances", "francine", "francis",
  "francisco", "franco", "francs", "frank", "frankie", "franklin", "frankly", "franz",
  "frasier", "fraud", "freak", "freaked", "freakin", "freaking", "freaks", "freaky", "fred",
  "freddie", "freddy", "frederick", "free", "freed", "freedom", "freely", "freeman", "freeze",
  "freezer", "freezing", "french", "frequency", "fresh", "freshman", "friday", "fridge",
  "fried", "friend", "friendly", "friends", "friendship", "fries", "frighten", "frightened",
  "frightening", "fritz", "frog", "frogs", "from", "front", "frost", "frozen", "fruit",
  "fruits", "frustrated", "frustrating", "fuck", "fucked", "fucker", "fuckers", "fuckin",
  "fucking", "fucks", "fuel", "fugitive", "fulfill", "fulfilled", "full", "fully", "function",
  "functions", "fund", "fundamental", "funding", "funds", "funeral", "funky", "funny",
  "furious", "furniture", "further", "fury", "fuse", "fuss", "future", "gabe", "gabriel",
  "gabrielle", "gail", "gain", "gained", "galaxy", "gallery", "gamble", "gambling", "game",
  "games", "gang", "gangs", "gangster", "gangsters", "garage", "garbage", "garcia", "garden",
  "gardener", "gardens", "garlic", "garrett", "gary", "gasoline", "gasp", "gasping", "gasps",
  "gate", "gates", "gather", "gathered", "gathering", "gave", "gavin", "gaze", "gear", "geek",
  "geez", "gemma", "gene", "general", "generally", "generals", "generation", "generations",
  "generator", "generous", "genes", "genetic", "genius", "gentle", "gentleman", "gentlemen",
  "gently", "genuine", "geoffrey", "george", "georgia", "georgie", "gerald", "gerard", "german",
  "germans", "germany", "gerry", "gestapo", "gesture", "gets", "gettin", "getting", "ghetto",
  "ghost", "ghosts", "giant", "giants", "gibbs", "gibson", "gideon", "gift", "gifted", "gifts",
  "gigantic", "giggles", "giggling", "gilbert", "gimme", "gina", "ginger", "giovanni", "girl",
  "girlfriend", "girlfriends", "girls", "give", "given", "gives", "giving", "glad", "gladly",
  "glance", "glass", "glasses", "glen", "glenn", "glimpse", "global", "globe", "gloria",
  "glorious", "glory", "glove", "gloves", "glow", "glowing", "glue", "goal", "goals", "goat",
  "goats", "goddamn", "goddess", "godfather", "gods", "goes", "goin", "going", "gold", "golden",
  "golf", "gone", "gong", "gonna", "good", "goodbye", "goodness", "goodnight", "goods",
  "google", "goose", "gordon", "gorgeous", "gorilla", "gosh", "gossip", "gotcha", "gotham",
  "gotta", "gotten", "government", "governor", "gown", "grab", "grabbed", "grabbing", "grace",
  "gracias", "gracious", "grade", "grades", "gradually", "graduate", "graduated", "graduation",
  "graham", "grain", "grams", "grand", "grandchildren", "granddad", "granddaughter",
  "grandfather", "grandma", "grandmother", "grandpa", "grandparents", "grandson", "granny",
  "grant", "granted", "grapes", "grasp", "grass", "grateful", "gratitude", "grave", "graves",
  "graveyard", "gravity", "gray", "grayson", "grease", "great", "greater", "greatest",
  "greatly", "greece", "greed", "greedy", "greek", "greeks", "green", "greene", "greet",
  "greeting", "greetings", "greg", "gregory", "grenade", "gretchen", "grew", "grey", "grid",
  "grief", "griffin", "grill", "grim", "grind", "grip", "groaning", "groans", "groceries",
  "grocery", "groom", "gross", "ground", "grounded", "grounds", "group", "groups", "grove",
  "grow", "growing", "growling", "growls", "grown", "grows", "growth", "grudge", "grunt",
  "grunting", "grunts", "guarantee", "guaranteed", "guard", "guardian", "guarding", "guards",
  "guess", "guessed", "guessing", "guest", "guests", "guidance", "guide", "guilt", "guilty",
  "guinea", "guitar", "gulf", "gunfire", "guns", "gunshot", "gunshots", "guru", "guts", "guys",
  "gwen", "gypsy", "habit", "habits", "hack", "hacked", "hadn", "hail", "hair", "haircut",
  "hairs", "hairy", "haley", "half", "halfway", "hall", "hallelujah", "halloween", "halls",
  "hallway", "halt", "hamilton", "hamlet", "hammer", "hammond", "hand", "handcuffs", "handed",
  "handful", "handing", "handkerchief", "handle", "handled", "handling", "hands", "handsome",
  "handwriting", "handy", "hang", "hanged", "hanging", "hangs", "hank", "hanna", "hannah",
  "hannibal", "hans", "happen", "happened", "happening", "happens", "happier", "happiest",
  "happily", "happiness", "happy", "harassment", "harbor", "hard", "harder", "hardest",
  "hardly", "hardware", "harley", "harm", "harmless", "harmony", "harold", "harper", "harriet",
  "harris", "harrison", "harry", "harsh", "hart", "harvard", "harvest", "harvey", "hasn",
  "hastings", "hatch", "hate", "hated", "hates", "hath", "hatred", "hats", "haul", "haunt",
  "haunted", "have", "haven", "having", "hawaii", "hawk", "hayes", "head", "headache",
  "headaches", "headed", "heading", "headmaster", "headquarters", "heads", "heal", "healed",
  "healing", "health", "healthy", "hear", "heard", "hearing", "hears", "heart", "heartbeat",
  "hearts", "heat", "heather", "heating", "heaven", "heavenly", "heavens", "heavily", "heavy",
  "heck", "hector", "heel", "heels", "heidi", "height", "heights", "heir", "held", "helen",
  "helena", "helicopter", "hell", "hello", "helmet", "help", "helped", "helpful", "helping",
  "helpless", "helps", "hence", "henderson", "henri", "henry", "herb", "herbert", "hercules",
  "herd", "here", "hereby", "heritage", "herman", "hero", "heroes", "heroic", "heroin", "herr",
  "hers", "herself", "hesitate", "hidden", "hide", "hideous", "hides", "hiding", "higgins",
  "high", "higher", "highest", "highly", "highness", "highway", "hike", "hilarious", "hilda",
  "hill", "hills", "himself", "hint", "hips", "hire", "hired", "hiring", "hissing", "historic",
  "historical", "history", "hitler", "hits", "hitting", "hiya", "hobby", "hockey", "hogan",
  "hold", "holding", "holds", "hole", "holes", "holiday", "holidays", "holland", "hollow",
  "holly", "hollywood", "holmes", "holt", "holy", "home", "homeland", "homeless", "homer",
  "homes", "hometown", "homework", "homicide", "homosexual", "honest", "honestly", "honesty",
  "honey", "honeymoon", "hong", "honking", "honks", "honor", "honorable", "honored", "honour",
  "hood", "hook", "hooked", "hooker", "hooray", "hope", "hoped", "hopefully", "hopeless",
  "hopes", "hoping", "horizon", "horn", "horns", "horny", "horrible", "horror", "horse",
  "horses", "hose", "hospital", "hospitality", "hospitals", "host", "hostage", "hostages",
  "hostile", "hotel", "hotels", "hotter", "hottest", "hour", "hours", "house", "household",
  "housekeeper", "houses", "housing", "houston", "howard", "howdy", "however", "howling",
  "hudson", "huge", "hugh", "hughes", "hugo", "hulk", "hull", "human", "humanity", "humans",
  "humble", "humiliated", "humiliating", "humiliation", "humming", "humor", "humour", "hunch",
  "hundred", "hundreds", "hung", "hunger", "hungry", "hunt", "hunted", "hunter", "hunters",
  "hunting", "hurricane", "hurry", "hurt", "hurting", "hurts", "husband", "husbands", "hush",
  "hustle", "hyah", "hysterical", "hyun", "idea", "ideal", "ideas", "identical",
  "identification", "identified", "identify", "identity", "idiot", "idiots", "idle", "idol",
  "ifyou", "ignorance", "ignorant", "ignore", "ignored", "ignoring", "igor", "iike", "illegal",
  "illness", "illusion", "image", "images", "imaginary", "imagination", "imagine", "imagined",
  "imagining", "imitates", "imitating", "immediate", "immediately", "immigration", "immortal",
  "immune", "immunity", "impact", "impatient", "imperial", "importance", "important",
  "importantly", "impossible", "impress", "impressed", "impression", "impressive", "imprisoned",
  "improve", "improved", "improvement", "impulse", "inappropriate", "inaudible", "inch",
  "inches", "incident", "include", "included", "includes", "including", "income", "incoming",
  "increase", "increased", "increasing", "incredible", "incredibly", "indeed", "independence",
  "independent", "india", "indian", "indians", "indicate", "indicates", "indistinct",
  "indistinctly", "individual", "individuals", "industrial", "industries", "industry",
  "inevitable", "infected", "infection", "infinite", "influence", "info", "inform", "informant",
  "information", "informed", "ingredients", "ingrid", "inhales", "inherit", "inheritance",
  "inherited", "initial", "initiative", "injection", "injured", "injuries", "injury",
  "injustice", "inmates", "inner", "innit", "innocence", "innocent", "inquiry", "insane",
  "insanity", "insect", "insects", "inside", "insight", "insist", "insisted", "insists",
  "inspection", "inspector", "inspiration", "inspire", "inspired", "installed", "instance",
  "instant", "instantly", "instead", "instinct", "instincts", "institute", "institution",
  "instructed", "instructions", "instructor", "instrument", "instrumental", "instruments",
  "insult", "insulted", "insulting", "insurance", "intact", "integrity", "intel",
  "intellectual", "intelligence", "intelligent", "intend", "intended", "intense", "intent",
  "intention", "intentions", "interest", "interested", "interesting", "interests", "interfere",
  "interference", "interior", "intern", "internal", "international", "internet",
  "interrogation", "interrupt", "interrupted", "interrupting", "intervention", "interview",
  "interviewed", "interviews", "intimate", "into", "introduce", "introduced", "introduction",
  "intruder", "invasion", "invent", "invented", "invention", "inventory", "invest", "invested",
  "investigate", "investigated", "investigating", "investigation", "investigations",
  "investigator", "investment", "investors", "invincible", "invisible", "invitation", "invite",
  "invited", "inviting", "involve", "involved", "involvement", "involves", "involving", "iove",
  "iran", "iraq", "ireland", "irene", "iris", "irish", "iron", "ironic", "irony", "irrelevant",
  "irresponsible", "isaac", "isabel", "isabella", "isabelle", "islam", "island", "islands",
  "isolated", "israel", "issue", "issued", "issues", "italian", "italy", "item", "items",
  "itself", "ivan", "jack", "jackass", "jacket", "jackie", "jackpot", "jackson", "jacob",
  "jacques", "jade", "jail", "jake", "jamal", "james", "jamie", "jammed", "jane", "janet",
  "jang", "janice", "janitor", "january", "japan", "japanese", "jared", "jasmine", "jason",
  "jasper", "javier", "jazz", "jealous", "jealousy", "jean", "jeanne", "jeannie", "jeans",
  "jeep", "jeez", "jeff", "jefferson", "jeffrey", "jelly", "jenkins", "jenna", "jennifer",
  "jenny", "jeong", "jeremy", "jerk", "jerks", "jerome", "jerry", "jersey", "jerusalem", "jess",
  "jesse", "jessica", "jessie", "jesus", "jewel", "jewelry", "jewels", "jewish", "jews", "jill",
  "jimmy", "jingle", "joan", "joanna", "jobs", "jock", "joel", "joey", "john", "johnny",
  "johnson", "join", "joined", "joining", "joint", "joke", "joker", "jokes", "joking", "jolly",
  "jonah", "jonas", "jonathan", "jones", "joon", "jordan", "jorge", "jose", "joseph", "josh",
  "joshua", "journal", "journalist", "journalists", "journey", "joyce", "juan", "jude", "judge",
  "judged", "judgement", "judges", "judging", "judgment", "judith", "judy", "juice", "juicy",
  "jules", "julia", "julian", "julie", "julien", "juliet", "juliette", "julio", "julius",
  "july", "jump", "jumped", "jumping", "jumps", "june", "jung", "jungle", "junior", "junk",
  "junkie", "jupiter", "jurisdiction", "jury", "just", "justice", "justify", "justin",
  "juvenile", "kane", "kang", "kansas", "kara", "karan", "karate", "karen", "karl", "karma",
  "kate", "katherine", "kathy", "katie", "keen", "keep", "keeper", "keeping", "keeps", "keith",
  "keller", "kelly", "kennedy", "kenneth", "kenny", "kent", "kept", "kettle", "kevin",
  "keyboard", "keys", "khan", "kick", "kicked", "kicking", "kicks", "kidding", "kiddo",
  "kidnap", "kidnapped", "kidnapping", "kidney", "kids", "kill", "killed", "killer", "killers",
  "killing", "kills", "kilometers", "kilos", "kind", "kinda", "kindly", "kindness", "kinds",
  "king", "kingdom", "kings", "kira", "kirby", "kirk", "kiss", "kissed", "kisses", "kissing",
  "kitchen", "kitt", "kitten", "kitty", "klaus", "knee", "kneel", "knees", "knew", "knife",
  "knight", "knights", "knives", "knock", "knocked", "knocking", "knocks", "knot", "knots",
  "know", "knowing", "knowledge", "known", "knows", "kong", "korea", "korean", "kris",
  "krishna", "kung", "kurt", "kyle", "label", "labor", "laboratory", "labour", "labs", "lacey",
  "lack", "ladder", "ladies", "lads", "lady", "laid", "lake", "lamb", "lame", "lamp", "lana",
  "lance", "land", "landed", "landing", "landlord", "lands", "landscape", "lane", "lang",
  "language", "languages", "laptop", "large", "larger", "largest", "larry", "laser", "last",
  "lasted", "lasts", "late", "lately", "later", "latest", "latin", "laugh", "laughed",
  "laughing", "laughs", "laughter", "launch", "launched", "laundry", "laura", "laurel",
  "lauren", "laurie", "lava", "lawn", "lawrence", "laws", "lawsuit", "lawyer", "lawyers",
  "layer", "layers", "laying", "lazy", "lead", "leader", "leaders", "leadership", "leading",
  "leads", "leaf", "league", "leah", "leak", "leaking", "lean", "leap", "learn", "learned",
  "learning", "learnt", "lease", "least", "leather", "leave", "leaves", "leaving", "lecture",
  "left", "legacy", "legal", "legally", "legend", "legendary", "legends", "legitimate", "legs",
  "lemon", "lemonade", "lena", "lend", "length", "lenny", "lens", "lent", "leon", "leonard",
  "leonardo", "lesbian", "leslie", "less", "lesson", "lessons", "lester", "lethal", "lets",
  "letter", "letters", "letting", "level", "levels", "lewis", "liam", "liar", "liars", "libby",
  "liberal", "liberty", "library", "licence", "license", "lick", "lied", "lies", "lieutenant",
  "life", "lifestyle", "lifetime", "lift", "lifted", "lifting", "light", "lighten", "lighter",
  "lighting", "lightly", "lightning", "lights", "like", "liked", "likely", "likes", "likewise",
  "liking", "lilly", "lily", "limb", "limit", "limited", "limits", "limo", "lincoln", "linda",
  "lindsay", "line", "lined", "lines", "ling", "lining", "link", "linked", "links", "lion",
  "lionel", "lions", "lips", "lipstick", "liquid", "liquor", "lisa", "lisbon", "list", "listed",
  "listen", "listened", "listening", "listens", "lists", "literally", "literature", "little",
  "live", "lived", "lively", "liver", "lives", "living", "lizard", "lizzie", "lloyd", "load",
  "loaded", "loading", "loads", "loan", "loans", "lobby", "lobster", "local", "locals",
  "locate", "located", "location", "locations", "lock", "locked", "locker", "locking", "locks",
  "lodge", "logan", "logic", "logical", "logs", "lois", "lola", "london", "lone", "loneliness",
  "lonely", "long", "longer", "longest", "longing", "look", "looked", "lookin", "looking",
  "lookout", "looks", "loop", "loose", "loosen", "lord", "lords", "lordship", "lorenzo", "lori",
  "lose", "loser", "losers", "loses", "losing", "loss", "losses", "lost", "lots", "lottery",
  "loud", "louder", "loudly", "louie", "louis", "louise", "lounge", "lousy", "love", "loved",
  "lovejoy", "lovely", "lover", "lovers", "loves", "loving", "lower", "lowest", "loyal",
  "loyalty", "luca", "lucas", "lucia", "luck", "luckily", "lucky", "lucy", "luggage", "luis",
  "luke", "lulu", "lump", "lunatic", "lunch", "lung", "lungs", "lure", "lust", "luther",
  "luxury", "lydia", "lying", "lynn", "lyrics", "macgyver", "machine", "machinery", "machines",
  "mack", "madam", "madame", "maddie", "made", "mademoiselle", "madison", "madman", "madness",
  "madonna", "madrid", "maestro", "mafia", "magazine", "magazines", "maggie", "magic",
  "magical", "magician", "magistrate", "magnetic", "magnificent", "magnum", "maid", "maiden",
  "mail", "mails", "main", "mainland", "mainly", "maintain", "maintenance", "majesty", "major",
  "majority", "make", "maker", "makes", "makeup", "makin", "making", "malcolm", "male", "males",
  "mall", "mallory", "malone", "mama", "mamma", "manage", "managed", "management", "manager",
  "managing", "manchester", "mandy", "manhattan", "maniac", "manipulate", "mankind", "manner",
  "manners", "mannix", "manny", "mansion", "manual", "manuel", "many", "maps", "marathon",
  "marble", "marc", "marcel", "march", "marching", "marco", "marcus", "margaret", "marge",
  "maria", "marianne", "marie", "marijuana", "marilyn", "marina", "marine", "marines", "mario",
  "marion", "mark", "marked", "market", "marketing", "marks", "marquis", "marriage", "married",
  "marry", "marrying", "mars", "marsh", "marshal", "marshall", "marta", "martha", "martial",
  "martin", "martini", "marty", "marvellous", "marvelous", "marvin", "mary", "mask", "masks",
  "mason", "mass", "massacre", "massage", "masses", "massive", "master", "masterpiece",
  "masters", "match", "matched", "matches", "matching", "mate", "material", "materials",
  "mates", "math", "matt", "matter", "matters", "matthew", "matthews", "mattress", "matty",
  "mature", "maureen", "maurice", "maximum", "maxwell", "maya", "maybe", "mayor", "mccoy",
  "mcgee", "meal", "meals", "mean", "meaning", "meaningless", "means", "meant", "meantime",
  "meanwhile", "measure", "measures", "meat", "mechanic", "mechanical", "mechanism", "medal",
  "media", "medic", "medical", "medication", "medicine", "medieval", "medium", "meds", "meet",
  "meeting", "meetings", "meets", "megan", "melanie", "melissa", "melody", "melt", "melted",
  "melting", "member", "members", "memo", "memorial", "memories", "memory", "mental",
  "mentally", "mention", "mentioned", "mentor", "menu", "mercedes", "merchandise", "merchant",
  "merci", "mercury", "mercy", "mere", "meredith", "merely", "merlin", "mermaid", "merry",
  "mess", "message", "messages", "messed", "messenger", "messing", "messy", "metal", "meter",
  "meters", "meth", "method", "methods", "metres", "metro", "mexican", "mexico", "miami",
  "mice", "michael", "michel", "michelle", "mick", "mickey", "microphone", "microwave",
  "middle", "midnight", "midst", "might", "mighty", "miguel", "mike", "mikey", "milan", "mild",
  "mile", "miles", "military", "milk", "mill", "miller", "millie", "million", "millionaire",
  "millions", "mills", "milo", "mimi", "mind", "minds", "mine", "mines", "ming", "mini",
  "minimum", "mining", "minister", "ministry", "minor", "mint", "minus", "minute", "minutes",
  "miracle", "miracles", "miranda", "miriam", "mirror", "mirrors", "miserable", "misery",
  "misfortune", "miss", "missed", "misses", "missile", "missiles", "missing", "mission",
  "missions", "mississippi", "missus", "missy", "mistake", "mistaken", "mistakes", "mister",
  "mistress", "misunderstanding", "misunderstood", "mitch", "mitchell", "mixed", "mixing",
  "moaning", "moans", "mobile", "mock", "mode", "model", "models", "modern", "modest", "mold",
  "mole", "molly", "moment", "moments", "momma", "mommy", "moms", "mona", "monastery", "monday",
  "money", "monica", "monitor", "monitoring", "monk", "monkey", "monkeys", "monks", "monroe",
  "monsieur", "monster", "monsters", "montana", "month", "monthly", "months", "monty", "mood",
  "moon", "moonlight", "moore", "moose", "moral", "more", "morgan", "morgue", "morning",
  "moron", "morphine", "morris", "morse", "mortal", "mortgage", "moscow", "moses", "mosque",
  "moss", "most", "mostly", "motel", "mother", "motherfucker", "motherfuckers", "motherfucking",
  "mothers", "motion", "motive", "motor", "motorcycle", "motto", "mount", "mountain",
  "mountains", "mourning", "mouse", "moustache", "mouth", "mouths", "move", "moved", "movement",
  "movements", "moves", "movie", "movies", "moving", "much", "muffled", "mulder", "mule",
  "multiple", "mumbai", "mumbling", "mummy", "murder", "murdered", "murderer", "murderers",
  "murdering", "murders", "murdoch", "murmuring", "murphy", "murray", "muscle", "muscles",
  "museum", "mushrooms", "music", "musical", "musician", "musicians", "muslim", "muslims",
  "must", "mustache", "mustard", "mustn", "mutant", "mute", "muttering", "mutual", "mwah",
  "myself", "mysteries", "mysterious", "mystery", "myth", "nadia", "nail", "nailed", "nails",
  "naive", "naked", "name", "named", "names", "nana", "nancy", "nanny", "naomi", "naples",
  "napoleon", "narcotics", "narrating", "narrator", "narrow", "nasa", "nash", "nasty",
  "natalie", "natasha", "nate", "nathan", "nation", "national", "nations", "native", "natural",
  "naturally", "nature", "naughty", "naval", "navy", "nazi", "nazis", "nder", "neal", "near",
  "nearby", "nearest", "nearly", "neat", "necessarily", "necessary", "neck", "necklace", "need",
  "needed", "needing", "needle", "needles", "needn", "needs", "negative", "negotiate",
  "negotiations", "negro", "neighbor", "neighborhood", "neighbors", "neighbour",
  "neighbourhood", "neighbours", "neil", "neither", "nelson", "nephew", "nerd", "nerve",
  "nerves", "nervous", "nest", "network", "neutral", "never", "nevertheless", "newest", "newly",
  "news", "newspaper", "newspapers", "newton", "next", "nice", "nicely", "nicer", "nicest",
  "nicholas", "nick", "nickel", "nickname", "nicky", "nico", "nicole", "niece", "nigel",
  "nigga", "nigger", "night", "nightclub", "nightmare", "nightmares", "nights", "nikita",
  "nikki", "niles", "nina", "nine", "ninja", "ninth", "nkoo", "noah", "noble", "nobody", "noel",
  "noise", "noises", "noisy", "nolan", "none", "nonsense", "noodles", "noon", "nope", "nora",
  "norm", "norma", "normal", "normally", "norman", "north", "northern", "nose", "noses", "note",
  "notebook", "noted", "notes", "nothin", "nothing", "notice", "noticed", "notify", "notion",
  "notorious", "novel", "november", "nowadays", "nowhere", "nuclear", "nude", "nuisance",
  "numb", "number", "numbers", "numerous", "nurse", "nursery", "nurses", "nursing", "nuts",
  "nypd", "oath", "obama", "obey", "object", "objection", "objective", "objects", "obligation",
  "obliged", "observation", "observe", "observed", "obsessed", "obsession", "obtain", "obvious",
  "obviously", "occasion", "occasionally", "occasions", "occupation", "occupied", "occur",
  "occurred", "ocean", "oceans", "october", "odds", "offence", "offend", "offended", "offense",
  "offensive", "offer", "offered", "offering", "offers", "office", "officer", "officers",
  "offices", "official", "officially", "officials", "often", "ofthe", "ohhh", "ohio", "okay",
  "older", "oldest", "olga", "olive", "oliver", "olivia", "ollie", "olympic", "olympics",
  "omar", "ominous", "once", "ones", "onion", "onions", "online", "only", "onto", "oooh",
  "oops", "open", "opened", "opening", "openly", "opens", "opera", "operate", "operating",
  "operation", "operations", "operator", "opinion", "opinions", "oppa", "opponent",
  "opportunities", "opportunity", "opposed", "opposite", "opposition", "option", "options",
  "orange", "orbit", "orchestra", "order", "ordered", "ordering", "orders", "ordinary", "organ",
  "organic", "organization", "organize", "organized", "organs", "origin", "original",
  "originally", "orleans", "orphan", "orphanage", "orphans", "oscar", "other", "others",
  "otherwise", "otto", "ouch", "ought", "oughta", "ours", "ourselves", "outcome", "outer",
  "outfit", "outrageous", "outside", "outstanding", "outta", "oven", "over", "overall",
  "overboard", "overcome", "overheard", "overlapping", "overnight", "overseas", "overtime",
  "overwhelmed", "overwhelming", "owed", "owen", "owes", "owned", "owner", "owners", "owns",
  "oxford", "oxygen", "pablo", "pace", "pacific", "pack", "package", "packed", "packing",
  "packs", "pact", "paddy", "page", "pages", "paid", "paige", "pain", "painful", "pains",
  "paint", "painted", "painter", "painting", "paintings", "pair", "pairs", "pajamas",
  "pakistan", "palace", "paladin", "pale", "palm", "palmer", "pals", "pamela", "pancakes",
  "panda", "panel", "panic", "panicked", "panties", "panting", "pants", "papa", "paper",
  "papers", "paperwork", "parade", "paradise", "parallel", "paranoid", "pardon", "parent",
  "parents", "paris", "parish", "park", "parked", "parker", "parking", "parks", "parliament",
  "parlor", "parole", "parrot", "part", "partial", "participate", "particles", "particular",
  "particularly", "parties", "partly", "partner", "partners", "partnership", "parts", "party",
  "pass", "passage", "passed", "passenger", "passengers", "passes", "passing", "passion",
  "passionate", "passport", "passports", "password", "past", "pasta", "pastor", "patch", "path",
  "pathetic", "paths", "patience", "patient", "patients", "patricia", "patrick", "patrol",
  "pattern", "patterns", "patty", "paul", "paula", "pauline", "pause", "pawn", "paying",
  "payment", "payments", "pays", "peace", "peaceful", "peacefully", "peach", "peak", "peanut",
  "peanuts", "pearl", "pearls", "peas", "peasant", "peasants", "peculiar", "pedro", "peek",
  "peel", "peggy", "penalty", "pencil", "penelope", "penguin", "penis", "pennsylvania", "penny",
  "pension", "pentagon", "people", "peoples", "pepper", "percent", "percy", "perfect",
  "perfection", "perfectly", "perform", "performance", "performed", "performing", "perfume",
  "perhaps", "perimeter", "period", "permanent", "permanently", "permission", "permit",
  "permitted", "perry", "person", "personal", "personality", "personally", "personnel",
  "persons", "perspective", "persuade", "pervert", "pete", "peter", "peterson", "petition",
  "petrol", "pets", "petty", "peyton", "phantom", "pharmacy", "phase", "phenomenon", "phil",
  "philadelphia", "philip", "philippe", "phillip", "phillips", "philosophy", "phoebe",
  "phoenix", "phone", "phoned", "phones", "phony", "photo", "photograph", "photographer",
  "photographs", "photography", "photos", "phrase", "physical", "physically", "physician",
  "physics", "piano", "pick", "picked", "picking", "pickle", "pickles", "picks", "pickup",
  "picnic", "picture", "pictures", "piece", "pieces", "pier", "pierce", "pierre", "pies",
  "pigeon", "pigeons", "piggy", "pigs", "pike", "pile", "pill", "pillow", "pills", "pilot",
  "pilots", "pimp", "pinch", "pine", "ping", "pink", "pinky", "pint", "pipe", "piper", "pipes",
  "pirate", "pirates", "piss", "pissed", "pissing", "pistol", "pitch", "pitched", "pitiful",
  "pity", "pizza", "place", "placed", "places", "plague", "plain", "plan", "plane", "planes",
  "planet", "planets", "planned", "planning", "plans", "plant", "planted", "plants", "plastic",
  "plate", "plates", "platform", "platoon", "play", "played", "player", "players", "playground",
  "playing", "plays", "plea", "plead", "pleasant", "please", "pleased", "pleasure", "pledge",
  "plenty", "plot", "plug", "plumber", "plus", "pocket", "pockets", "poem", "poems", "poet",
  "poetry", "point", "pointed", "pointing", "pointless", "points", "poirot", "poison",
  "poisoned", "poisoning", "poisonous", "poke", "poker", "poland", "polar", "pole", "poles",
  "police", "policeman", "policemen", "policy", "polish", "polite", "political", "politician",
  "politicians", "politics", "polly", "pond", "pony", "pool", "poop", "poor", "popcorn", "pope",
  "popped", "popping", "poppy", "pops", "popular", "population", "porch", "pork", "porn",
  "port", "portal", "porter", "portion", "portrait", "portuguese", "pose", "position",
  "positions", "positive", "positively", "possess", "possessed", "possession", "possibilities",
  "possibility", "possible", "possibly", "post", "posted", "poster", "posters", "potato",
  "potatoes", "potential", "potentially", "potion", "potter", "pound", "pounding", "pounds",
  "pour", "poured", "pouring", "poverty", "powder", "powell", "power", "powerful", "powers",
  "practical", "practically", "practice", "practicing", "prague", "praise", "prank", "pray",
  "prayed", "prayer", "prayers", "praying", "preacher", "precinct", "precious", "precise",
  "precisely", "predator", "predators", "predict", "predicted", "prefer", "preferred",
  "pregnancy", "pregnant", "preliminary", "premises", "prep", "preparation", "prepare",
  "prepared", "preparing", "prescription", "presence", "present", "presentation", "presented",
  "presents", "preserve", "president", "presidential", "press", "pressed", "pressing",
  "pressure", "preston", "presume", "pretend", "pretended", "pretending", "prettier", "pretty",
  "prevent", "previous", "previously", "prey", "price", "priceless", "prices", "prick", "pride",
  "priest", "priests", "primary", "prime", "primitive", "prince", "princess", "principal",
  "principle", "principles", "print", "printed", "printing", "prints", "prior", "priority",
  "prison", "prisoner", "prisoners", "privacy", "private", "privilege", "priya", "prize",
  "probably", "probation", "probe", "problem", "problems", "procedure", "procedures", "proceed",
  "process", "processing", "produce", "produced", "producer", "producers", "producing",
  "product", "production", "products", "profession", "professional", "professionals",
  "professor", "profile", "profit", "profits", "profound", "program", "programme", "programmed",
  "programs", "progress", "project", "projects", "prom", "promise", "promised", "promises",
  "promising", "promote", "promoted", "promotion", "pronounce", "proof", "propaganda", "proper",
  "properly", "properties", "property", "prophecy", "prophet", "proposal", "propose",
  "proposed", "proposition", "prosecution", "prosecutor", "prostitute", "prostitutes",
  "protect", "protected", "protecting", "protection", "protective", "protein", "protest",
  "protocol", "proud", "prove", "proved", "proven", "proves", "provide", "provided", "provides",
  "providing", "province", "proving", "psst", "psych", "psychiatric", "psychiatrist", "psychic",
  "psycho", "psychological", "psychologist", "psychology", "public", "publicity", "publicly",
  "publish", "published", "publisher", "pudding", "puff", "puke", "pull", "pulled", "pulling",
  "pulls", "pulse", "pump", "pumping", "pumpkin", "punch", "punched", "punching", "punish",
  "punished", "punishment", "punk", "pupils", "puppet", "puppies", "puppy", "purchase",
  "purchased", "pure", "purely", "purple", "purpose", "purposes", "purse", "pursue", "pursuit",
  "push", "pushed", "pushing", "pussy", "puts", "putting", "puzzle", "pyramid", "qualified",
  "qualities", "quality", "quantum", "quarrel", "quarter", "quarters", "queen", "queens",
  "queer", "quest", "question", "questioned", "questioning", "questions", "quick", "quicker",
  "quickly", "quid", "quiet", "quietly", "quinn", "quit", "quite", "quitting", "quiz", "quote",
  "rabbi", "rabbit", "rabbits", "race", "races", "rachel", "racing", "racist", "rack", "racket",
  "radar", "radiation", "radical", "radio", "radius", "rage", "rahul", "raid", "rail",
  "railroad", "railway", "rain", "rainbow", "raining", "rains", "raise", "raised", "raising",
  "raja", "rally", "ralph", "ramsay", "ranch", "randall", "random", "randy", "rang", "range",
  "ranger", "rangers", "rank", "ranks", "ransom", "rape", "raped", "rapid", "rapidly", "rapist",
  "rare", "rarely", "rascal", "rash", "rate", "rates", "rather", "rational", "rats", "rattling",
  "raven", "ravi", "raymond", "rays", "razor", "reach", "reached", "reaches", "reaching",
  "react", "reaction", "read", "reader", "reading", "readings", "reads", "ready", "reagan",
  "real", "realise", "realised", "realistic", "reality", "realize", "realized", "really",
  "realm", "rear", "reason", "reasonable", "reasons", "rebecca", "rebel", "rebellion", "rebels",
  "rebuild", "recall", "receipt", "receive", "received", "receiving", "recent", "recently",
  "reception", "recipe", "reckless", "reckon", "recognise", "recognition", "recognize",
  "recognized", "recommend", "recommendation", "recommended", "reconsider", "record",
  "recorded", "recorder", "recording", "records", "recover", "recovered", "recovery", "recruit",
  "reduce", "reduced", "reed", "reese", "refer", "reference", "referred", "referring",
  "reflect", "reflection", "reform", "refrigerator", "refuge", "refugees", "refuse", "refused",
  "refuses", "refusing", "regard", "regarding", "regardless", "regards", "reggie", "regime",
  "regiment", "regina", "region", "register", "registered", "registration", "regret", "regrets",
  "regular", "regularly", "regulations", "rehab", "rehearsal", "rehearse", "reid", "reign",
  "reinforcements", "reject", "rejected", "relate", "related", "relation", "relations",
  "relationship", "relationships", "relative", "relatively", "relatives", "relax", "relaxed",
  "relaxing", "release", "released", "relevant", "reliable", "relief", "relieve", "relieved",
  "religion", "religious", "rely", "remain", "remained", "remaining", "remains", "remarkable",
  "remember", "remembered", "remembering", "remembers", "remind", "reminded", "reminder",
  "reminds", "remote", "remove", "removed", "rendezvous", "rene", "rent", "rental", "rented",
  "repair", "repairs", "repay", "repeat", "repeated", "repeatedly", "repeating", "replace",
  "replaced", "replacement", "reply", "report", "reported", "reporter", "reporters",
  "reporting", "reports", "represent", "representative", "represented", "representing",
  "represents", "republic", "republican", "reputation", "request", "requested", "requesting",
  "requests", "require", "required", "requires", "rescue", "rescued", "research", "resent",
  "reservation", "reservations", "reserve", "reserved", "residence", "resident", "residents",
  "resign", "resignation", "resist", "resistance", "resolve", "resolved", "resort", "resources",
  "respect", "respectable", "respected", "respects", "respond", "responding", "response",
  "responsibilities", "responsibility", "responsible", "rest", "restaurant", "restaurants",
  "resting", "restless", "restore", "restored", "result", "results", "resume", "retarded",
  "retire", "retired", "retirement", "retreat", "retrieve", "return", "returned", "returning",
  "returns", "reunion", "reveal", "revealed", "revenge", "reverend", "reverse", "review",
  "revolution", "revolutionary", "revving", "reward", "reynolds", "rhythm", "ribs", "rice",
  "rich", "richard", "richie", "rick", "ricky", "rico", "riddle", "ride", "rider", "rides",
  "ridge", "ridiculous", "riding", "rifle", "rifles", "right", "righteous", "rights", "riley",
  "ring", "ringing", "rings", "riot", "ripe", "ripped", "ripping", "rise", "rises", "rising",
  "risk", "risked", "risking", "risks", "risky", "rita", "ritual", "rival", "river", "rivers",
  "road", "roads", "roam", "roar", "roaring", "roars", "roast", "robbed", "robber", "robbers",
  "robbery", "robbie", "robbing", "robe", "robert", "roberto", "roberts", "robin", "robinson",
  "robot", "robots", "rock", "rocket", "rocking", "rocks", "rocky", "rode", "rodney", "roger",
  "rogers", "rogue", "roland", "role", "roles", "roll", "rolled", "roller", "rolling", "rolls",
  "roman", "romance", "romans", "romantic", "rome", "romeo", "ronald", "ronnie", "roof",
  "rookie", "room", "roommate", "rooms", "roosevelt", "rooster", "root", "roots", "rope",
  "ropes", "rory", "rosa", "rose", "rosemary", "roses", "rosie", "ross", "rotten", "rough",
  "roughly", "round", "rounds", "route", "routine", "royal", "rubber", "rubbing", "rubbish",
  "ruby", "rude", "rudy", "ruin", "ruined", "ruining", "ruins", "rule", "ruled", "ruler",
  "rules", "ruling", "rumbling", "rumor", "rumors", "runner", "running", "runs", "runway",
  "rupees", "rupert", "rush", "rushed", "rushing", "russ", "russell", "russia", "russian",
  "russians", "rustling", "rusty", "ruth", "ruthless", "ryan", "sabotage", "sabrina", "sack",
  "sacred", "sacrifice", "sacrificed", "sacrifices", "saddle", "sadie", "sadly", "sadness",
  "safe", "safely", "safer", "safety", "sage", "said", "sail", "sailed", "sailing", "sailor",
  "sailors", "saint", "saints", "sake", "sakes", "salad", "salary", "sale", "sales", "salesman",
  "sally", "salmon", "salon", "salt", "salute", "salvation", "samantha", "same", "sammy",
  "sample", "samples", "samuel", "samurai", "sanctuary", "sand", "sanders", "sandra",
  "sandwich", "sandwiches", "sandy", "sane", "sang", "santa", "sara", "sarah", "sarge", "sasha",
  "satan", "satellite", "satisfaction", "satisfied", "satisfy", "saturday", "sauce", "saul",
  "sausage", "savage", "save", "saved", "saves", "saving", "savings", "savior", "sayin",
  "saying", "says", "scale", "scam", "scan", "scandal", "scar", "scare", "scared", "scares",
  "scarf", "scaring", "scars", "scary", "scattered", "scenario", "scene", "scenes", "scent",
  "schedule", "scheduled", "scheme", "schmidt", "scholar", "scholarship", "school", "schools",
  "schultz", "science", "scientific", "scientist", "scientists", "scissors", "scoffs", "scoop",
  "scooter", "score", "scored", "scores", "scotch", "scotland", "scott", "scottish", "scotty",
  "scoundrel", "scout", "scouts", "scrap", "scratch", "scratching", "scream", "screamed",
  "screaming", "screams", "screech", "screeching", "screen", "screenplay", "screw", "screwed",
  "screwing", "script", "scrub", "scully", "scum", "scumbag", "seal", "sealed", "seals", "sean",
  "search", "searched", "searching", "seas", "season", "seasons", "seat", "seated", "seats",
  "seattle", "sebastian", "second", "secondary", "seconds", "secret", "secretary", "secretly",
  "secrets", "section", "sector", "secure", "secured", "security", "seduce", "seed", "seeds",
  "seeing", "seek", "seeking", "seem", "seemed", "seems", "seen", "sees", "seize", "seized",
  "select", "selected", "selection", "self", "selfish", "sell", "selling", "sells", "semester",
  "senate", "senator", "send", "sending", "sends", "senior", "senor", "sensation", "sense",
  "sensei", "senses", "sensible", "sensitive", "sensors", "sent", "sentence", "sentenced",
  "sentences", "sentimental", "seoul", "separate", "separated", "separation", "september",
  "sequence", "serena", "sergeant", "serial", "series", "serious", "seriously", "servant",
  "servants", "serve", "served", "server", "serves", "service", "services", "serving",
  "session", "sessions", "seth", "sets", "setting", "settle", "settled", "settlement",
  "settling", "setup", "seven", "seventeen", "seventh", "several", "severe", "sewer", "sewing",
  "sexual", "sexually", "sexy", "shack", "shade", "shadow", "shadows", "shaft", "shake",
  "shaken", "shakespeare", "shaking", "shall", "shallow", "shame", "shameless", "shan", "shane",
  "shanghai", "shannon", "shape", "shaped", "shapes", "share", "shared", "shares", "sharing",
  "shark", "sharks", "sharon", "sharp", "sharply", "shattered", "shave", "shaved", "shaw",
  "shawn", "shed", "sheep", "sheer", "sheet", "sheets", "sheila", "shelby", "sheldon", "shelf",
  "shell", "shells", "shelly", "shelter", "shepherd", "sheriff", "sherlock", "sherman",
  "sherry", "shhh", "shield", "shields", "shift", "shifts", "shin", "shine", "shines",
  "shining", "shiny", "ship", "shipment", "shipped", "shipping", "ships", "shirley", "shirt",
  "shirts", "shit", "shitting", "shitty", "shiva", "shock", "shocked", "shocking", "shoe",
  "shoes", "shook", "shoot", "shooter", "shooting", "shoots", "shop", "shopping", "shops",
  "shore", "short", "shorter", "shortly", "shorts", "shorty", "shot", "shotgun", "shots",
  "should", "shoulder", "shoulders", "shouldn", "shout", "shouted", "shouting", "shouts",
  "shove", "shovel", "show", "showed", "shower", "showers", "showing", "shown", "shows",
  "shrieks", "shrimp", "shrine", "shrink", "shut", "shuts", "shutter", "shutting", "shuttle",
  "sick", "sickness", "side", "sides", "sidney", "sigh", "sighing", "sighs", "sight", "sights",
  "sign", "signal", "signals", "signature", "signed", "significant", "signing", "signs",
  "silence", "silent", "silk", "silly", "silver", "similar", "simon", "simone", "simple",
  "simply", "simpson", "since", "sincere", "sincerely", "sing", "singer", "singh", "singing",
  "single", "sings", "sink", "sinking", "sins", "sire", "siren", "sirens", "sister", "sisters",
  "site", "sites", "sits", "sitting", "situation", "situations", "sixteen", "sixth", "sixty",
  "size", "skeleton", "sketch", "skies", "skill", "skilled", "skills", "skin", "skinny", "skip",
  "skipped", "skipper", "skirt", "skull", "slack", "slam", "slams", "slap", "slapped",
  "slaughter", "slaughtered", "slave", "slavery", "slaves", "sleep", "sleeping", "sleeps",
  "sleepy", "sleeve", "slept", "slice", "slick", "slide", "slight", "slightest", "slightly",
  "slim", "slip", "slipped", "slippers", "slippery", "slipping", "slit", "sloppy", "slot",
  "slow", "slower", "slowly", "slut", "smack", "small", "smaller", "smallest", "smart",
  "smarter", "smash", "smashed", "smashing", "smell", "smelled", "smelling", "smells", "smile",
  "smiled", "smiles", "smiling", "smith", "smoke", "smoked", "smokes", "smoking", "smooth",
  "smuggling", "snack", "snacks", "snake", "snakes", "snap", "snapped", "snaps", "snarling",
  "snatch", "sneak", "sneaking", "sniff", "sniffing", "sniffles", "sniffs", "sniper", "snoring",
  "snow", "snuck", "soaked", "soap", "sobbing", "sober", "sobs", "soccer", "social", "society",
  "sock", "socks", "soda", "sofa", "sofia", "soft", "softly", "software", "soil", "solar",
  "sold", "soldier", "soldiers", "sole", "solid", "solitary", "solo", "solomon", "solution",
  "solve", "solved", "some", "somebody", "someday", "somehow", "someone", "someplace",
  "somethin", "something", "sometime", "sometimes", "somewhat", "somewhere", "song", "songs",
  "sonia", "sonic", "sonny", "sons", "soon", "sooner", "sophia", "sophie", "sophisticated",
  "sore", "sorrow", "sorry", "sort", "sorted", "sorts", "sought", "soul", "souls", "sound",
  "sounded", "sounding", "sounds", "soup", "sour", "source", "sources", "south", "southern",
  "souvenir", "soviet", "space", "spaceship", "spaghetti", "spain", "spanish", "spare",
  "spared", "spark", "speak", "speaker", "speaking", "speaks", "spear", "special", "specialist",
  "specially", "specialty", "species", "specific", "specifically", "spectacular", "speech",
  "speeches", "speed", "speeding", "spell", "spells", "spencer", "spend", "spending", "spends",
  "spent", "sperm", "spice", "spicy", "spider", "spies", "spike", "spill", "spilled", "spin",
  "spine", "spinning", "spirit", "spirits", "spiritual", "spit", "spite", "splash", "splendid",
  "split", "splitting", "spock", "spoil", "spoiled", "spoke", "spoken", "sponge", "sponsor",
  "spoon", "sport", "sports", "spot", "spots", "spotted", "spray", "spread", "spreading",
  "spring", "springs", "spying", "squad", "squadron", "square", "squeaking", "squeal",
  "squealing", "squeeze", "squirrel", "stab", "stabbed", "stable", "stacey", "stack", "stacy",
  "stadium", "staff", "stage", "stages", "stain", "stairs", "stake", "stakes", "stalin",
  "stalker", "stalking", "stall", "stammering", "stammers", "stamp", "stamps", "stan", "stand",
  "standard", "standards", "standing", "stands", "stanley", "star", "stare", "staring", "stark",
  "starring", "stars", "start", "started", "starting", "starts", "starve", "starving", "stash",
  "state", "stated", "statement", "statements", "states", "static", "station", "stations",
  "statue", "status", "stay", "stayed", "staying", "stays", "steady", "steak", "steal",
  "stealing", "steals", "steam", "steed", "steel", "steele", "steer", "steering", "stefan",
  "stella", "step", "stephanie", "stephen", "stepped", "stepping", "steps", "stereo", "stern",
  "steve", "steven", "stevens", "stevie", "stew", "stewart", "stick", "sticking", "sticks",
  "sticky", "stiff", "still", "sting", "stink", "stinking", "stinks", "stir", "stitch",
  "stitches", "stock", "stole", "stolen", "stomach", "stone", "stoned", "stones", "stood",
  "stop", "stopped", "stopping", "stops", "storage", "store", "stored", "stores", "stories",
  "storm", "storms", "story", "stove", "straight", "straighten", "strain", "strange",
  "strangely", "stranger", "strangers", "strangle", "strangled", "strap", "strategy", "straw",
  "strawberry", "stray", "streak", "stream", "street", "streets", "strength", "stress",
  "stressed", "stretch", "strict", "strictly", "strike", "strikes", "striking", "string",
  "strings", "strip", "stripped", "stripper", "stroke", "stroll", "strong", "stronger",
  "strongest", "strongly", "struck", "structure", "struggle", "struggling", "stuart",
  "stubborn", "stuck", "stud", "student", "students", "studied", "studies", "studio", "study",
  "studying", "stuff", "stuffed", "stunning", "stunt", "stupid", "style", "subject", "subjects",
  "submarine", "submit", "substance", "substitute", "subtitles", "subtle", "subway", "succeed",
  "succeeded", "success", "successful", "successfully", "such", "suck", "sucked", "sucker",
  "sucking", "sucks", "sudden", "suddenly", "suffer", "suffered", "suffering", "sufficient",
  "sugar", "suggest", "suggested", "suggesting", "suggestion", "suggestions", "suggests",
  "suicide", "suit", "suitable", "suitcase", "suite", "suits", "sullivan", "sultan", "summer",
  "summit", "summon", "summoned", "sunday", "sundays", "sung", "sunglasses", "sunk", "sunlight",
  "sunny", "sunrise", "sunset", "sunshine", "super", "superb", "superhero", "superintendent",
  "superior", "superman", "supermarket", "supernatural", "supervisor", "supper", "supplies",
  "supply", "support", "supported", "supporting", "supportive", "suppose", "supposed",
  "supposedly", "supreme", "sure", "surely", "surf", "surface", "surgeon", "surgery",
  "surgical", "surprise", "surprised", "surprises", "surprising", "surprisingly", "surrender",
  "surrounded", "surrounding", "surveillance", "survey", "survival", "survive", "survived",
  "surviving", "survivor", "survivors", "susan", "sushi", "susie", "suspect", "suspected",
  "suspects", "suspended", "suspenseful", "suspension", "suspicion", "suspicious", "sustained",
  "suzanne", "swallow", "swallowed", "swamp", "swan", "swap", "swear", "sweat", "sweater",
  "sweating", "sweaty", "sweden", "swedish", "sweep", "sweet", "sweetest", "sweetheart",
  "sweetie", "sweets", "swell", "swept", "swift", "swim", "swimming", "swine", "swing",
  "swinging", "swiss", "switch", "switched", "switzerland", "sword", "swords", "swore", "sworn",
  "sydney", "sylvia", "symbol", "symbols", "sympathy", "symptoms", "sync", "syndrome", "syrup",
  "system", "systems", "table", "tables", "tackle", "taco", "tactical", "tactics", "tail",
  "tails", "take", "taken", "takes", "takin", "taking", "tale", "talent", "talented", "talents",
  "tales", "talk", "talked", "talkin", "talking", "talks", "tall", "taller", "tammy", "tang",
  "tango", "tank", "tanks", "tanner", "tanya", "tape", "tapes", "tapping", "tara", "target",
  "targets", "tarzan", "task", "taste", "tasted", "tastes", "tasty", "tate", "tattoo",
  "tattoos", "taught", "taxes", "taxi", "taylor", "teach", "teacher", "teachers", "teaches",
  "teaching", "team", "teams", "tear", "tearing", "tears", "tease", "teasing", "tech",
  "technical", "technically", "technique", "techniques", "technology", "teddy", "teen",
  "teenage", "teenager", "teenagers", "teeth", "telegram", "telephone", "telescope",
  "television", "tell", "tellin", "telling", "tells", "temper", "temperature", "temperatures",
  "temple", "temporarily", "temporary", "temptation", "tempted", "tend", "tender", "tennis",
  "tens", "tense", "tension", "tent", "tenth", "tequila", "teresa", "term", "terminal", "terms",
  "terrace", "terrible", "terribly", "terrific", "terrified", "terrifying", "territory",
  "terror", "terrorism", "terrorist", "terrorists", "terry", "tess", "tessa", "test", "tested",
  "testify", "testimony", "testing", "tests", "texas", "text", "texted", "texting", "texts",
  "thai", "thailand", "than", "thank", "thankful", "thanks", "thanksgiving", "that", "thats",
  "theater", "theatre", "thee", "theft", "their", "theirs", "them", "theme", "themselves",
  "then", "theo", "theories", "theory", "therapist", "therapy", "there", "therefore", "theresa",
  "these", "they", "thick", "thief", "thieves", "thin", "thing", "things", "think", "thinkin",
  "thinking", "thinks", "third", "thirst", "thirsty", "thirteen", "thirty", "this", "thomas",
  "thompson", "thor", "thorough", "thoroughly", "those", "thou", "though", "thought",
  "thoughtful", "thoughts", "thousand", "thousands", "thread", "threat", "threaten",
  "threatened", "threatening", "threats", "three", "threw", "thrill", "thrilled", "throat",
  "throne", "through", "throughout", "throw", "throwing", "thrown", "throws", "thrust", "thud",
  "thuds", "thugs", "thumb", "thunder", "thursday", "thus", "tick", "ticket", "tickets",
  "ticking", "tickle", "tide", "tidy", "tied", "ties", "tiffany", "tiger", "tigers", "tight",
  "till", "time", "timer", "times", "timing", "timmy", "timothy", "tina", "tiny", "tipped",
  "tips", "tire", "tired", "tires", "tissue", "title", "tits", "toad", "toast", "tobacco",
  "toby", "today", "todd", "toes", "together", "toilet", "toilets", "token", "tokyo", "told",
  "tolerate", "toll", "tomato", "tomatoes", "tomb", "tommy", "tomorrow", "tone", "tongue",
  "toni", "tonight", "tons", "tony", "took", "tool", "tools", "tooth", "toothbrush", "topic",
  "tops", "torch", "tore", "torment", "torn", "torture", "tortured", "torturing", "toss",
  "tossed", "total", "totally", "touch", "touched", "touches", "touching", "tough", "tougher",
  "tour", "tourist", "tourists", "tournament", "toward", "towards", "towel", "towels", "tower",
  "towers", "town", "towns", "toxic", "toys", "trace", "traced", "traces", "track", "tracked",
  "tracking", "tracks", "tractor", "tracy", "trade", "traded", "trading", "tradition",
  "traditional", "traditions", "traffic", "tragedy", "tragic", "trail", "trailer", "train",
  "trained", "trainer", "training", "trains", "traitor", "traitors", "tramp", "transfer",
  "transferred", "transform", "transformed", "transition", "translate", "translated",
  "translation", "translator", "transmission", "transplant", "transport", "transportation",
  "trap", "trapped", "traps", "trash", "trauma", "travel", "traveled", "traveling", "travelled",
  "travelling", "travels", "travis", "tray", "treason", "treasure", "treasures", "treat",
  "treated", "treating", "treatment", "treats", "treaty", "tree", "trees", "trembling",
  "tremendous", "trent", "trevor", "trial", "trials", "triangle", "tribal", "tribe", "tribes",
  "tribute", "trick", "tricked", "tricks", "tricky", "tried", "tries", "trigger", "triggered",
  "trip", "triple", "tripped", "trips", "trish", "triumph", "troop", "troops", "trophy",
  "tropical", "trouble", "troubled", "troubles", "troubling", "trousers", "troy", "truck",
  "trucks", "true", "truly", "trump", "trumpet", "trunk", "trust", "trusted", "trusting",
  "trusts", "truth", "tryin", "trying", "tube", "tubes", "tuck", "tucker", "tuesday", "tumor",
  "tuna", "tune", "tunnel", "tunnels", "turf", "turk", "turkey", "turkish", "turn", "turned",
  "turner", "turning", "turns", "turtle", "turtles", "tutor", "twelve", "twenty", "twice",
  "twilight", "twin", "twins", "twist", "twisted", "twitter", "tying", "tyler", "type", "types",
  "typical", "typing", "ugly", "ultimate", "ultimately", "umbrella", "unable", "unacceptable",
  "unarmed", "unbearable", "unbelievable", "uncle", "uncomfortable", "unconscious", "under",
  "undercover", "underestimate", "underground", "underneath", "understand", "understandable",
  "understanding", "understands", "understood", "underwater", "underwear", "underworld", "undo",
  "unemployed", "unexpected", "unfair", "unfinished", "unfortunate", "unfortunately",
  "ungrateful", "unhappy", "uniform", "uniforms", "union", "unique", "unit", "unite", "united",
  "units", "unity", "universal", "universe", "university", "unknown", "unless", "unlike",
  "unlikely", "unlock", "unlucky", "unnecessary", "unpleasant", "unpredictable", "unstable",
  "unsub", "untie", "until", "unto", "unusual", "upbeat", "update", "upon", "upper", "upset",
  "upsetting", "upside", "upstairs", "urban", "urge", "urgent", "urine", "used", "useful",
  "useless", "uses", "using", "usual", "usually", "utter", "utterly", "vacation", "vacuum",
  "vagina", "vague", "vain", "valentine", "valerie", "valid", "valley", "valuable", "value",
  "values", "valve", "vampire", "vampires", "vanessa", "vanilla", "vanish", "vanished",
  "variety", "various", "vase", "vast", "vault", "vega", "vegas", "vegetable", "vegetables",
  "vegetarian", "vehicle", "vehicles", "veil", "veins", "vengeance", "venice", "vent",
  "venture", "venus", "vera", "verdict", "verify", "vernon", "veronica", "verse", "version",
  "versus", "very", "vessel", "vessels", "vest", "vibe", "vice", "vicious", "vicki", "vicky",
  "victim", "victims", "victor", "victoria", "victory", "video", "videos", "vienna", "vietnam",
  "vietnamese", "view", "viewers", "views", "vijay", "vile", "villa", "village", "villagers",
  "villages", "villain", "vince", "vincent", "violated", "violation", "violence", "violent",
  "violet", "violin", "virgin", "virginia", "virginity", "virtually", "virtue", "virus", "visa",
  "visible", "vision", "visions", "visit", "visited", "visiting", "visitor", "visitors",
  "visits", "visual", "vital", "vivian", "vodka", "voice", "voiceover", "voices", "void",
  "volcano", "volume", "volunteer", "volunteered", "volunteers", "vomit", "vote", "voted",
  "votes", "voting", "vows", "voyage", "vulgar", "vulnerable", "wade", "wage", "wages",
  "wagner", "wagon", "wailing", "waist", "wait", "waited", "waiter", "waiting", "waitress",
  "waits", "wake", "wakes", "waking", "walk", "walked", "walker", "walking", "walks", "wall",
  "wallace", "wallet", "walls", "wally", "walsh", "walt", "walter", "waltz", "wanda", "wander",
  "wandering", "wang", "wanna", "want", "wanted", "wanting", "wants", "ward", "warden",
  "wardrobe", "warehouse", "warm", "warmer", "warming", "warmth", "warn", "warned", "warner",
  "warning", "warp", "warrant", "warren", "warrior", "warriors", "wars", "wash", "washed",
  "washing", "washington", "wasn", "waste", "wasted", "wasting", "watch", "watched", "watches",
  "watching", "water", "waters", "watson", "wave", "waves", "waving", "wayne", "ways", "weak",
  "weakness", "wealth", "wealthy", "weapon", "weapons", "wear", "wearing", "wears", "weather",
  "weaver", "website", "wedding", "weddings", "wednesday", "weed", "week", "weekend",
  "weekends", "weekly", "weeks", "weep", "weigh", "weight", "weird", "weirdo", "welcome",
  "welfare", "well", "wells", "wendy", "went", "were", "weren", "werewolf", "wesley", "west",
  "western", "whack", "whale", "whales", "what", "whatever", "whatsoever", "wheat", "wheel",
  "wheelchair", "wheeler", "wheels", "when", "whenever", "where", "whereabouts", "whereas",
  "wherever", "whether", "whew", "which", "while", "whilst", "whimpering", "whimpers",
  "whining", "whip", "whipped", "whirring", "whiskey", "whisky", "whisper", "whispering",
  "whispers", "whistle", "whistles", "whistling", "white", "whites", "whitney", "whoa",
  "whoever", "whole", "whom", "whoo", "whooping", "whoops", "whore", "whores", "whose",
  "wicked", "wide", "widow", "wife", "wild", "wilderness", "will", "william", "williams",
  "willie", "willing", "willow", "willy", "wilson", "wind", "window", "windows", "winds",
  "wine", "wing", "wings", "winner", "winners", "winning", "wins", "winston", "winter", "wipe",
  "wiped", "wire", "wired", "wires", "wisdom", "wise", "wish", "wished", "wishes", "wishing",
  "witch", "witches", "with", "withdraw", "within", "without", "witness", "witnessed",
  "witnesses", "wives", "wizard", "woke", "wolf", "wolves", "woman", "womb", "women", "wonder",
  "wondered", "wonderful", "wondering", "wonders", "wong", "wont", "wood", "wooden", "woods",
  "woody", "wool", "word", "words", "wore", "work", "worked", "worker", "workers", "workin",
  "working", "works", "workshop", "world", "worlds", "worldwide", "worm", "worms", "worn",
  "worried", "worries", "worry", "worrying", "worse", "worship", "worst", "worth", "worthless",
  "worthy", "would", "wouldn", "wound", "wounded", "wounds", "wrap", "wrapped", "wrath",
  "wreck", "wrecked", "wrestling", "wretched", "wrist", "write", "writer", "writers", "writes",
  "writing", "written", "wrong", "wrote", "wyatt", "xena", "xiao", "yacht", "yale", "yang",
  "yankee", "yard", "yards", "yeah", "year", "years", "yell", "yelled", "yelling", "yellow",
  "yells", "yesterday", "yield", "yoga", "yoon", "york", "young", "younger", "youngest", "your",
  "yours", "yourself", "yourselves", "youth", "yuan", "yuck", "yummy", "yuri", "zach", "zack",
  "zero", "zeus", "zhang", "zombie", "zombies", "zone", "zoom",
]);
