"use client";

import { useEffect, useState } from "react";

export default function CertificatePage() {
  const [downloadUrl, setDownloadUrl] = useState("/cert/download");

  useEffect(() => {
    // Use the current host for the download URL
    const protocol = window.location.protocol;
    const host = window.location.host;
    setDownloadUrl(`${protocol}//${host}/cert/download`);
  }, []);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Install Certificate - OBS Live Suite</title>
      </head>
      <body
        style={{
          fontFamily:
            "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
          maxWidth: "600px",
          margin: "0 auto",
          padding: "20px",
          background: "#1a1a2e",
          color: "#eee",
          lineHeight: 1.6,
          minHeight: "100vh",
          boxSizing: "border-box",
        }}
      >
        <h1 style={{ color: "#00d4ff", marginBottom: "10px" }}>
          Install Certificate
        </h1>
        <p>
          To use OBS Live Suite on your mobile device, you need to install the
          root CA certificate.
        </p>

        <a
          href={downloadUrl}
          style={{
            display: "inline-block",
            background: "#00d4ff",
            color: "#1a1a2e",
            padding: "15px 30px",
            textDecoration: "none",
            borderRadius: "8px",
            fontWeight: "bold",
            fontSize: "18px",
            margin: "20px 0",
          }}
        >
          Download Certificate
        </a>

        <div style={{ marginBottom: "40px" }}>
          <h2 style={{ color: "#ff6b6b", marginTop: "30px" }}>
            iOS Instructions
          </h2>
          <ol style={{ paddingLeft: "20px" }}>
            <li style={{ margin: "10px 0" }}>Tap the download button above</li>
            <li style={{ margin: "10px 0" }}>
              A prompt will appear: &quot;This website is trying to download a
              configuration profile&quot; → Tap <strong>Allow</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Go to <strong>Settings</strong> → <strong>General</strong> →{" "}
              <strong>VPN &amp; Device Management</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Find the downloaded profile and tap <strong>Install</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Enter your passcode if prompted
            </li>
            <li style={{ margin: "10px 0" }}>
              Go to <strong>Settings</strong> → <strong>General</strong> →{" "}
              <strong>About</strong> →{" "}
              <strong>Certificate Trust Settings</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Enable full trust for the <strong>mkcert</strong> certificate
            </li>
          </ol>
        </div>

        <div style={{ marginBottom: "40px" }}>
          <h2 style={{ color: "#ff6b6b", marginTop: "30px" }}>
            Android Instructions
          </h2>
          <ol style={{ paddingLeft: "20px" }}>
            <li style={{ margin: "10px 0" }}>Tap the download button above</li>
            <li style={{ margin: "10px 0" }}>
              Go to <strong>Settings</strong> → <strong>Security</strong> →{" "}
              <strong>Encryption &amp; Credentials</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Tap <strong>Install a certificate</strong> →{" "}
              <strong>CA Certificate</strong>
            </li>
            <li style={{ margin: "10px 0" }}>
              Select the downloaded{" "}
              <code
                style={{
                  background: "#333",
                  padding: "2px 6px",
                  borderRadius: "4px",
                }}
              >
                rootCA.crt
              </code>{" "}
              file
            </li>
            <li style={{ margin: "10px 0" }}>Confirm the installation</li>
          </ol>
          <p>
            <em>
              Note: Menu location may vary by Android version and manufacturer.
            </em>
          </p>
        </div>

        <div
          style={{
            background: "#ff6b6b22",
            borderLeft: "4px solid #ff6b6b",
            padding: "15px",
            margin: "20px 0",
          }}
        >
          <strong>Security Note:</strong> This certificate is only valid for
          your local network. Only install it on devices you trust and control.
          The certificate was generated by mkcert on your computer.
        </div>
      </body>
    </html>
  );
}
